# Generated by Django 5.1.5 on 2025-02-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='film_images/'),
        ),
    ]
