# Generated by Django 5.1.5 on 2025-02-02 09:49

import tiket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0002_film_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=tiket.models.film_image_path),
        ),
    ]
